### ISSUE TITLE
fatal error: mptcpd/config-private.h: No such file or directory

### ISSUE THREAD

**Issue by apnavik** [intel/mptcpd#63] opened 2019-12-30 08:09 UTC
Compile time error with the yocto framework:
error log summary: plugins/path_managers/sspi.c:20:11: fatal error: mptcpd/config-private.h: No such file or directory

**Comment by ossama-othman** [comment] 2020-01-07 04:50
The header `<mptcpd/config-private.h>` is automatically generated, and should exist in the directory `include/mptcpd` in the build tree after a successful run of the `configure` script.

Did you modify build flags (e.g., `CPPFLAGS` or `CFLAGS`)?  Can you provide steps to reproduce the problem?

**Comment by ossama-othman** [comment] 2020-05-08 21:50
@apnavik Is this still a problem for you?  If not, I'd like to close this issue.

Thanks!

**Comment by tachiniererin** [comment] 2020-05-26 10:34
I just hit this bug too. I checked out master, ran bootstrap and created a build directory and ran configure in it. When then running make, it fails with the same error.

This does not happen when running configure and make in the source directory.

**Comment by ossama-othman** [comment] 2020-05-26 20:00
Thanks for letting me know how to reproduce the problem!  I've confirmed the problem, and will fix it shortly.

I'm a bit surprised this problem occurs since I assume it would have been caught by `make distcheck` since it, too, runs a `VPATH` based buiild.

**Comment by ossama-othman** [comment] 2020-05-26 20:19
Pull request #73 fixes the problem for me.  Please give it a try if you get a chance.  Thanks!

**Closed** 2020-05-27 00:00 UTC
Labels: bug

**Comment by ossama-othman** [comment] 2020-06-13 03:33
[mptcpd 0.5](https://github.com/intel/mptcpd/releases/tag/v0.5) was just released. It fixes this problem.
